nirvachit/urls.py
from django.conf.urls import url
from django.urls import  path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from nirvachit import views
 

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    path('nirvachit/', include('pollapp.urls')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "NIRVACHIT"
admin.site.site_title = "NIRVACHIT"
admin.site.index_title = "NIRVACHIT"

pollapp/urls.py
from . import views
from django.conf.urls import url, include
from django.contrib.auth.views import (login, logout)

from django.contrib.auth import views as auth_views
from django.urls import path
app_name = 'pollapp'
urlpatterns = [
	url(r'^login/$',login,{'template_name' : 'pollapp/login.html'}),
	url(r'^logout/$',logout, {'template_name' : 'pollapp/logout.html'}),
	path('', views.post_list ,name = 'post_list'),
	path('<int:blog_id>/', views.details, name = "details"),
	# 
	path('register/', views.register, name = "register"),
	url(r'^like/$', views.like_post, name = "like_post"),
	path('news/', views.news, name = 'news'),
	path('about/', views.about, name = 'about'),
	path('former_minister/', views.chief_minister, name = 'chief_minister'),
	path('election_updates/', views.election_updates, name = 'election_updates'),
	path('news_letter/', views.send_newsletter, name = "news_letter"),
	path('election_update_details/<int:pk>', views.election_update_details, name = "election_update_details"),

	# url(r'^activate/(?P<uidb64>[0-9A-Za-z_\\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),
    
] 

pollapp/models.py
from django.db import models

# Create your models here.

from django.urls import reverse

# Create your models here.
from django.contrib.auth.models import User
from django.utils import timezone

class Post(models.Model):
	author = models.ForeignKey('auth.User', on_delete = models.CASCADE)
	title = models.CharField(max_length= 100)
	text = models.TextField()
	image = models.ImageField(upload_to = 'New/%Y/%m/%d', blank = True)
	created_date = models.DateTimeField(default = timezone.now)
	published_date = models.DateTimeField(blank = True, null = True)
	likes = models.ManyToManyField('auth.User', related_name = "likes" , blank = True)

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __str__(self):
		return self.title

	def total_likes(self):
		return self.likes.count()

	def get_absolute_url(self):
		return reverse("pollapp:details" , args = [self.id])

	class Meta:
		verbose_name = "Post"
		verbose_name_plural = "Post"

class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name = 'aa')
	user = models.ForeignKey(User , on_delete = models.CASCADE)
	# reply = models.ForeignKey('self', null = True, related_name = 'replies', blank = True, on_delete = models.CASCADE)
	content = models.TextField(max_length = 100)
	timestamp = models.DateTimeField(auto_now_add = True)

	def __str__(self):
		return '{}-{}'.format(self.post.title, str(self.user.username))

	class Meta:
		verbose_name = "Comment"
		verbose_name_plural = "Comment"

class News(models.Model):
	author = models.ForeignKey('auth.User', on_delete = models.CASCADE)
	title = models.CharField(max_length= 100)
	text = models.TextField()
	# simage = models.ImageField(upload_to = 'New/%Y/%m/%d', blank = True)
	created_date = models.DateTimeField(default = timezone.now)
	published_date = models.DateTimeField(blank = True, null = True)


	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("pollapp:details" , args = [self.id])

	class Meta:
		verbose_name = "News"
		verbose_name_plural = "News"


class Subscriber(models.Model):
	email = models.EmailField()

	def __str__(self):
		return str(self.email)

	class Meta:
		verbose_name = 'Subscriber'
		verbose_name_plural = 'Subscriber'


class SendNewsLetter(models.Model):
	title = models.CharField(max_length = 200, blank = True, verbose_name = "News Title")
	text = models.TextField()
	links = models.URLField()

	def __str__(self):
		return str(self.title)

	class Meta:
		verbose_name_plural = "News Letter"
		verbose_name = "News Letter"

class State(models.Model):
	state = models.CharField(max_length = 100)

	def __str__(self):
		return str(self.state)

	class Meta:
		verbose_name = "State"
		verbose_name_plural = "State"

class Party(models.Model):
	party = models.CharField(max_length = 100)

	def __str__(self):
		return str(self.party)

	class Meta:
		verbose_name = "Party"
		verbose_name_plural = "Party"


class ElectionUpdate(models.Model):
	state = models.ForeignKey(State, on_delete = models.CASCADE)
	party = models.ManyToManyField(Party, blank = True)
	total_no_of_seats = models.IntegerField(blank = True)
	result = models.TextField(null = True)

	def __str__(self):
		return str(self.state)

	class Meta:
		verbose_name = "Election Update"
		verbose_name_plural = "Election Update"	


class Ministry(models.Model):
	party = models.CharField(max_length = 100, blank = True)
	ministry = models.CharField(max_length = 100, blank = True)
	name = models.CharField(max_length = 100, blank = True)
	state = models.CharField(max_length = 100, blank = True)

	def __str__(self):	
		return str(self.name)

	class Meta:
		verbose_name = "Ministry"
		verbose_name_plural = "Ministry"

pollapp/forms.py
from django import forms
from .models import Comment, Subscriber, SendNewsLetter
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class RegistrationForm(UserCreationForm):
	email = forms.EmailField(required = True)
	# exmaple photo class : resolution pixel or info about model
	def __init__(self, *args, **kwargs):
		super(RegistrationForm, self).__init__(*args, **kwargs)
		for fieldname in ['username', 'email','password1', 'password2',]:
			self.fields[fieldname].help_text = None
	

	def clean_email(self):
		email = self.cleaned_data['email'].lower()
		r = User.objects.filter(email = email)
		if r.count():
			raise ValidationError("Email already exixts")
		return email

	class Meta:
		model = User
		fields = ('username', 'first_name' , 'last_name','email', 'password1', 'password2')

	def save(self,commit = True):
		user =  super(RegistrationForm, self).save(commit = False)
		user.first_name =  self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user



class CommentForm(forms.ModelForm):
	content = forms.CharField(label = "Comments" , widget = forms.Textarea(attrs = {'class' :'form-control' , 'placeholder' : 'Text goes here!!!' , 'rows':'4' , 'cols' : '50'}))
	class Meta:
		model = Comment
		fields = {'content',}

class NewsForm(forms.ModelForm):
	email = forms.EmailField(required = True, label = "User email")
	class Meta:
		model = Subscriber
		fields = '__all__'


class NewsLetterForm(forms.ModelForm):
	class Meta:
		model = SendNewsLetter
		fields = '__all__'

pollapp/views.py
from django.shortcuts import render
# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Post, Comment, News, Subscriber, State, Party, ElectionUpdate, Ministry
from .forms import RegistrationForm, CommentForm, NewsForm, NewsLetterForm
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.core.mail import send_mail
# Create your views here.


# About nirvachuit 
def about(request):
	print("Hello world")
	return render(request, 'pollapp/about.html')


# Election updates, all states list is shown
def election_updates(request):
	list_state = ElectionUpdate.objects.all()
	return render(request, 'pollapp/election_updates.html', {'list_state' : list_state})


# Paerticular state updates
def election_update_details(request, pk):
	data = get_object_or_404(ElectionUpdate, pk = pk)
	return render(request, "pollapp/election_update_details.html", {'data':data})

# List of chief ministers
def chief_minister(request):
	minister = Ministry.objects.all()
	return render(request, 'pollapp/minister.html', {'minister' : minister})

# News
def news(request):
	new = News.objects.all()
	context = {
	'new' : new
		}
	return render(request, 'pollapp/news.html',  context)



# News feed
@login_required
def post_list(request):
	posts = Post.objects.all()
	context = {
	'posts' : posts
	}
	if request.method == 'POST':
		form = NewsForm(request.POST or None)
		if form.is_valid():
			email = form.cleaned_data.get('email')
			email_save = Subscriber(email = email)
			email_save.save()
			return redirect('/nirvachit')
	else:
		form = NewsForm()
	return render(request, 'pollapp/post_list.html',  {'posts' : posts, 'form':form})


# Particular news feed 
@login_required
def details(request, blog_id):
	posts = get_object_or_404(Post, pk = blog_id)
	comments = Comment.objects.filter(post__title = posts)
	is_liked = False
	if posts.likes.filter(id = request.user.id).exists():
		is_liked = True

	if request.method == 'POST':
		comment_form = CommentForm(request.POST or None)
		if comment_form.is_valid():
			content = comment_form.cleaned_data.get('content')
			comment = Comment(user = request.user, content = content, post  = posts )
			comment.save()
			return HttpResponseRedirect(posts.get_absolute_url())
	else:
		comment_form = CommentForm()	
		context = {'posts' : posts, 'is_liked' : is_liked, 'total_likes' : posts.total_likes, 'comments' : comments, 'comment_form' : comment_form}
	return render(request, 'pollapp/details.html' , context )



# Like post
@login_required
def like_post(request):
	posts = get_object_or_404(Post, id = request.POST.get('post_id'))
	is_liked = False
	if posts.likes.filter(id = request.user.id).exists():
		posts.likes.remove(request.user)
		is_liked = False
	else:
		posts.likes.add(request.user)
		is_liked = True
	# posts.likes.add(request.user)
	return HttpResponseRedirect(posts.get_absolute_url())

def register(request):
	if request.method == 'POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/nirvachit/login/')
	else:
		form = RegistrationForm
	args = {'form' : form}
	return render(request, 'pollapp/reg_forms.html', args)


# News letter
@login_required
def send_newsletter(request):
	if request.user.is_staff:
		if request.method == "POST":
			form = NewsLetterForm(request.POST)
			try:
				if form.is_valid():
					post = form.save(commit=False)
					all_subscriber = Subscriber.objects.all()	
					email = []
					for i in all_subscriber:
						email.append(i.email)
					complete_mail = post.title + "\n" + post.text + "\n" + post.links
					send_mail(post.title, complete_mail, 'gautamamber5@gmail.com', email)
					post.save()
					return redirect('/nirvachit/')
			except:
				print("Sorry something went wrong")
		else:
			form = NewsLetterForm()
		return render(request, "pollapp/news_letter.html", {"form":form})
	else:
		return render(request, "pollapp/no_news_letter.html")





	

pollapp/templates/pollapp/about.html
		{% extends 'base.html' %}
{% block body %}
	
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<br>
<br>
<div class="container">
	<div class="jumbotron jumbotron-fluid">
	<br>
  <div class="container">
    <center><h3 class="display-4">About Nirvachit</h3></center>
    <center><p class="lead w3-justify" >Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p></center>
  </div>
</div>
</div>
	{% endblock %}

pollapp/templates/pollapp/chief_minister.html
{% extends 'base.html' %}
{% block body %}
<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {
    background-color: #dddddd;
}
</style>
<center><h2>Chief Ministers</h2></center>
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<center>
	<table>
  <tr>
    <th>State/Union Territory</th>
    <th>Name</th>
    <th>Ministry</th>
    <th>Party</th>
  </tr>
{% for i in minister %}
  <tr>
    <td>{{i.state}}</td>
    <td>{{i.name}}</td>
    <td>{{i.ministry}}</td>
    <td>{{i.party}}</td>
  </tr>
{% endfor %}
</table>
			</center>
		</div>
	</div>
</div>

{% endblock %}

pollapp/templates/pollapp/details.html
{% extends 'base.html' %}
{% block body %}
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<style>
input[type=submit] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
} 
</style>
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<h1><b>{{ posts.title }}</b></h1>
			
			<br>
	<img src="{{ posts.image.url }}" alt="Post nirvachit" class="img-responsive"><br>
	<br>
	{{ posts.text }}
	<p>
		<br><b>{{ total_likes }} Like{{ total_likes | pluralize }}</b>
	</p>
	<hr>

	<form action="{% url 'pollapp:like_post' %}" method="post">
	{% csrf_token %}
	{% if is_liked %}
		<button type="submit" name="post_id" value="{{ posts.id }}">DisLike</button>
	{% else %}
	<button type="submit" name="post_id" value="{{posts.id}}">Like</button>
	{% endif %}
</form>

		</div>
	</div>
</div>





<div class="container">

<div class="main-comment-section">
<form method="POST">
	{% csrf_token %}
	{{ comment_form.as_p }}

	<input type="submit" value="Submit">
	
</form>
{{ comments.count }} Comment{{ comments|pluralize }}
	{% for comment in comments %}
	 <blockquote class="blockquote">
  <p class="mb-0">{{ comment.content }}</p>
  <footer class="blockquote-footer">by: <cite title="Source Title">{{comment.user|capfirst}}</cite>
<!-- <button type="button" name="button" class="rply-btn  btn-outline-dark btn-sm ml-2">Reply</button>
 -->
  </footer>
</blockquote>


<div class="replied-comments coontainer mt-2" style="display: none;"> 
{% for reply in comment.replies.all %}
 <blockquote class="blockquote">
  <p class="mb-0"><small>{{ reply.content }}</p>
  <footer class="blockquote-footer"> by: <cite title="Source Title">{{reply.user|capfirst}}</cite></small>



  </footer>
</blockquote>

{% endfor %}
	<div class="form-group row">
		<form method="POST">
	{% csrf_token %}
	<input type="hidden" name="comment_id" value="{{ comment.id }}">
	{{ comment_form.as_p }}
{% if request.user.is_authenticated %}
	<input type="submit" value="Submit">
	{% else %}
	<H3>sorry</H3>

{% endif %}
</form> 
	</div>
</div>


	{% endfor %}
</div>
</div>

{% endblock %}

pollapp/templates/pollapp/election_update_details.html
{% extends 'base.html' %}
{% block body %}
{% load static %}

<div class="container">
    <div class="row">
        <div>
            <h3>
                <b>
                    State: {{ data.state }}
                </b>
            </h3>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div>
            <h3>
                <b>
                    Total Seats: {{ data.total_no_of_seats }}
                </b>
            </h3>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div>
            <h3>
                <b>
                    Parties : {% for parties in data.party.all %} {{ parties }} {% endfor %}
                </b>
            </h3>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div>
            <h3>
                <b>
                    Result: {{ data.result }}
                </b>
            </h3>
        </div>
    </div>
</div>


{% endblock %}

pollapp/templates/pollapp/election_updates.html
{% extends 'base.html' %}
{% block body %}

<center><h2><b>Election 2019</b></h2></center>

<br>
<br>


	{% for i in list_state %}
	<h1 style="margin-left: 40px;"><b><a href="{% url 'pollapp:election_update_details' i.id %}">{{ i.state }}</a></b></h1><br>
	{% endfor %}



{% endblock %}

pollapp/templates/pollapp/form.html
{% load form_tags widget_tweaks %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}

{% for field in form %}
  <div class="form-group">
    {{ field.label_tag }}
    {% render_field field class=field|input_class %}
    {% for error in field.errors %}
      <div class="invalid-feedback">
        {{ error }}
      </div>
    {% endfor %}
    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
{% endfor %}

pollapp/templates/pollapp/former_minister.html
{% extends 'base.html' %}
{% block body %}
<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {
    background-color: #dddddd;
}
</style>
<center><h2>Former Ministers</h2></center>
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<center>
				<table>
  <tr>
    <th>State/Union Territory</th>
    <th>Cheif Minister</th>
    <th>Party</th>
  </tr>
  <tr>
    <td>Andhra Pradesh</td>
    <td>Shri. Nara Chandrababu Naidu</td>
    <td>Telugu Desam Party</td>
  </tr>
  <tr>
    <td>Centro comercial Moctezuma</td>
    <td>Francisco Chang</td>
    <td>Mexico</td>
  </tr>
  <tr>
    <td>Ernst Handel</td>
    <td>Roland Mendel</td>
    <td>Austria</td>
  </tr>
  <tr>
    <td>Island Trading</td>
    <td>Helen Bennett</td>
    <td>UK</td>
  </tr>
  <tr>
    <td>Laughing Bacchus Winecellars</td>
    <td>Yoshi Tannamuri</td>
    <td>Canada</td>
  </tr>
  <tr>
    <td>Magazzini Alimentari Riuniti</td>
    <td>Giovanni Rovelli</td>
    <td>Italy</td>
  </tr>
</table>
			</center>
		</div>
	</div>
</div>

{% endblock %}

pollapp/templates/pollapp/login.html
{% extends 'base.html' %}
{% block body %}
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<br><br>
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <center>
        <b>
          <i>
            <h2 style="color: orange;">क्या सिर्फ चुनावों तक अपना मत सीमित रखना उचित है,</h2>
<h1>आइये अपने मत का प्रयोग करें चुनाव से पहले भी चुनाव के बाद भी </h1>
<h1 style="color: green;">एक जागरूक समाज के ओर अग्रसर कदम!!
          </i></h1>
        </b>
      </center>
    </div>
  </div>
</div>

<br>
<br>
<br>

<div class="container">
  <div class="row">
    <div class="col-sm-5 col-xs-12">
      <div class="jumbotron jumbotron-fluid">
  
   <div class="container">
<h3>Login</h3>
<form method="POST">
{% csrf_token %}
{{ form.as_p }}
<button class = "buttonmy" type="submit">Login</button>
<h3><a href="/nirvachit/register/">Register</a></h3>
<br>
</form>
</div>
 </div>
</div>

<div class="col-sm-7 col-xs-12">
<h3>
  <ul>
  <li>
    Bad officials are elected by good citizens who don’t vote.
  </li>
  <li>
    The ballot is stronger than the bullet.
  </li>
  <li>
    One of the penalties for refusing to participate in politics is that you end up being governed by your inferiors.
  </li>
  <li>
    The ignorance of one voter in a democracy impairs the security of all.
  </li>
  <li>
    Always vote for principle, though you may vote alone, and you may cherish the sweetest reflection that your vote is never lost.
  </li>
  <li>
    If you don’t vote, you lose the right to complain.
  </li>
  <li>
    A man without a vote is a man without protection.
  </li>
  <li>
    Someone struggled for your right to vote. Use it.
  </li>
</ul>
</h3>

</div>
</div>
</div>

<div class="container">
  <div class="container">
    <hr>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <center>
        <h2><b>Follow us on:</b></h2>
      </center>
    </div>
  </div>
</div>



<div class="container-fluid" style="font-size: 40px;">
  <div class="row">
    <div class="col-xs-12 logo">
       <center>

       <!-- Gmail link -->

       <a href="" data-toogle= "tooltip" data-placement = "bottom" title="Shoot a mail" class="social_icons social"><i class="fa fa-envelope" ></i></a>

      

       <!-- Twitter link -->

<a href="" data-toogle= "tooltip" data-placement = "bottom" title="Twitter" class="social_icons social social"><i class="fa fa-twitter" ></i></a>

      <!-- Youtube link -->

<a href="" data-toogle= "tooltip" data-placement = "bottom" title="Youtube" class="social_icons social"><i class="fa fa-youtube-play"></i></a>

      <!-- Instagram link -->

<a href="" data-toogle= "tooltip" data-placement = "bottom" title="Instagram" class="social_icons social"><i class="fa fa-instagram"></i></a>

  <!-- Facebook link -->

<a href=""  data-toogle= "tooltip" data-placement = "bottom" title="Facebook" class="social_icons social"><i class="fa fa-facebook" ></i></a>
      

<br>
</center>

    </div>
    
  </div>
</div>


<script>
var myIndex = 0;
carousel();

function carousel() {
    var i;
    var x = document.getElementsByClassName("mySlides");
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";  
    }
    myIndex++;
    if (myIndex > x.length) {myIndex = 1}    
    x[myIndex-1].style.display = "block";  
    setTimeout(carousel, 2000); // Change image every 2 seconds
}
</script>	





{% endblock %}

pollapp/templates/pollapp/logout.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h3 class="display-4">You are successfully logout.</h3>
    <p class="lead">Again Login: <a href="/nirvachit/login/">Login</a></p>
  </div>
</div>
</div>

{% endblock %}

pollapp/templates/pollapp/minister.html
{% extends 'base.html' %}
{% block body %}
<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {
    background-color: #dddddd;
}
</style>
<center><h2>Ministers</h2></center>
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<center>
	<table>
  <tr>
    <th>State/Union Territory</th>
    <th>Name</th>
    <th>Ministry</th>
    <th>Party</th>
  </tr>
{% for i in minister %}
  <tr>
    <td>{{i.state}}</td>
    <td>{{i.name}}</td>
    <td>{{i.ministry}}</td>
    <td>{{i.party}}</td>
  </tr>
{% endfor %}
</table>
			</center>
		</div>
	</div>
</div>

{% endblock %}

pollapp/templates/pollapp/news.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<center><h1><b style="font-family: monospace;">Daily News</b></h1></center>
		</div>
	</div>
</div>
<br>
<div class="container">
	<div class="row">
		<div class="col-xs-12">
				<div class="jumbotron jumbotron-fluid">
				<br>
					{% for news_list in new %}
				<h2><b>{{ news_list.title }}</b></h2>
				<h3>{{ news_list.text|linebreaksbr }}<h3>
				<hr>
				{% endfor %}
				</div>
		</div>
	</div>
</div>

{% endblock %}

pollapp/templates/pollapp/news_letter.html
{% extends 'base.html' %}
{% block body %}
<style>
	input[type=text] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}
	input[type=url] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}
textarea{
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}


input[type=submit] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}
</style>
<center>
	<h1>
		<i>New Article</i>
	</h1>
</center>

<br>
<br>

	<form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit"> 
    </form>


{% endblock %}

pollapp/templates/pollapp/no_news_letter.html
{% extends 'base.html' %}
{% block body %}

<center>
	<h1>
		Sorry, you are not authorize to send news letter
	</h1>
</center>

{% endblock %}

pollapp/templates/pollapp/reg_forms.html
{% extends 'base.html' %}
{% block body %}

<style>
	input[type=text] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}
input[type=email] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}
input[type=password] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}
input[type=submit] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}
</style>
<center><b style="font-size: 40px; font-family: monospace;">Registration</b></center>

<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<form method="POST">
	{% csrf_token %}
	{{ form.as_p }}
<input type="submit" value="Register">
</form>

		</div>
	</div>
</div>

{% endblock %}